[package]
name = "oxide-langchain-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.88"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = { version = "1.16.0", features = ["v4"] }
tracing = "0.1.41"
