[package]
name = "oxide-langchain-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp-serde = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
syn = "2.0.100"
