[package]
name = "main-test"
version = "0.1.0"
edition = "2024"

[dependencies]
oxide-langchain = { version = "0.1.0", path = "../oxide-langchain"}
reqwest = "0.12.15"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
